// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_addstudent.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_registersubjects.cpp"
#include "EWIEGA46WW/moc_removestudent.cpp"
#include "EWIEGA46WW/moc_removesubject.cpp"
#include "EWIEGA46WW/moc_searchstudent.cpp"
#include "EWIEGA46WW/moc_subjectcalculations.cpp"
